kind: Service
apiVersion: v1
metadata:
  name: analytics-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: analytics-service
  type: LoadBalancer
  loadBalancerIP: 34.77.117.11 # "[your Analytics IP address]"
